=begin
Simple Inventory API

This is a simple API

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Reports::WordsDailyReport < Reports::BaseReport
end
