=begin
Simple Inventory API

This is a simple API

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Reports::WordsDailyReport < Reports::BaseReport
  ENV['KEYWORDS'].split(',').each do |keyword|
    field keyword.to_s, type: Integer
  end
end
