=begin
Simple Inventory API

This is a simple API

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'GET', '/', controller_name: 'reports', action_name: 'tweets_by_minute'
  add_swagger_route 'GET', '/trump_twitter_api/1.0.0/tweets_by_minute', controller_name: 'reports', action_name: 'tweets_by_minute'
  add_swagger_route 'GET', '/trump_twitter_api/1.0.0/tweets_daily', controller_name: 'reports', action_name: 'tweets_daily'
  add_swagger_route 'GET', '/trump_twitter_api/1.0.0/words_daily', controller_name: 'reports', action_name: 'words_daily'
end
