=begin
Simple Inventory API

This is a simple API

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ReportsController < ApplicationController
  def tweets_by_minute
    expires_in 1.day, public: true
    render json: Reports::TweetHourReport.all.as_json(except: '_id')
                   .map {|report_json| dates_to_number(report_json)}
  end

  def tweets_daily
    expires_in 1.day, public: true
    render json: Reports::TweetDailyReport.all.as_json(except: '_id')
                   .map {|report_json| dates_to_number(report_json)}
  end

  def words_daily
    expires_in 1.day, public: true
    render json: Reports::WordsDailyReport.all.as_json(except: '_id')
                   .map {|report_json| dates_to_number(report_json)}
  end

  private

  def dates_to_number(report_json)
    report_json['date'] = report_json['date'].to_time.to_i
    report_json
  end
end
